#!/usr/bin/env node
// Copyright 2026 Misael Monterroca
// SPDX-License-Identifier: Apache-2.0

// Parchea src/generated/ast.ts después de `tygo generate`.
//
// tygo genera tipos por parseo estático de Go, así que no puede enumerar los
// implementadores de una interfaz (ast.Element es una interfaz Go). Emite
// `export type Element = Node;` (Node = any), que hay que reemplazar por la
// unión discriminada real.
//
// La lista de miembros de la unión NO se hardcodea acá: se deriva del schema ya
// generado (schema/ast.schema.json), que contiene la unión como los $ref de
// $defs.ContentBlock.properties.elements.items.oneOf (gen-schema los emite desde
// su lista `elementTypes`, en orden). Así `elementTypes` (Go) queda como única
// fuente de verdad — atada a los implementadores reales de element() por el test
// TestElementTypesCoversAllImplementers en cmd/gen-schema — y esta lista deja de
// poder desincronizarse (issue #61).

const fs = require("fs");
const path = require("path");

// Deriva los nombres de la unión Element leyendo el schema generado.
function readElementUnion() {
  const schemaPath = path.join(
    __dirname,
    "..",
    "..",
    "schema",
    "ast.schema.json"
  );
  let schema;
  try {
    schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
  } catch (e) {
    console.error(
      "postprocess.cjs: no se pudo leer/parsear el schema en " +
        schemaPath +
        " (" +
        e.message +
        "). Corré 'go run ./cmd/gen-schema' primero."
    );
    process.exit(1);
  }
  const oneOf =
    schema &&
    schema.$defs &&
    schema.$defs.ContentBlock &&
    schema.$defs.ContentBlock.properties &&
    schema.$defs.ContentBlock.properties.elements &&
    schema.$defs.ContentBlock.properties.elements.items &&
    schema.$defs.ContentBlock.properties.elements.items.oneOf;
  if (!Array.isArray(oneOf) || oneOf.length === 0) {
    console.error(
      "postprocess.cjs: no se encontró $defs.ContentBlock.properties.elements.items.oneOf en el schema. " +
        "¿Cambió la forma que emite gen-schema? Revisar manualmente."
    );
    process.exit(1);
  }
  return oneOf.map((s) => String(s.$ref).replace("#/$defs/", ""));
}

const ELEMENT_UNION = readElementUnion();

const astTsPath = path.join(__dirname, "..", "src", "generated", "ast.ts");
let content = fs.readFileSync(astTsPath, "utf8");

// tygo mapea diagnostics.Position -> "Position" vía type_mappings, pero no
// agrega el import entre archivos generados (eso solo aplica dentro de un
// mismo `packages:` — ast y diagnostics se generan por separado).
const importHeader = '// Code generated by tygo. DO NOT EDIT.\n';
const positionImport = 'import type { Position } from "./diagnostics";\n';
if (!content.includes(positionImport)) {
  if (!content.startsWith(importHeader)) {
    console.error(
      "postprocess.cjs: no se encontró el header esperado de tygo al inicio de " +
        astTsPath +
        ". El output de tygo pudo haber cambiado de formato; revisar manualmente."
    );
    process.exit(1);
  }
  content = content.replace(
    importHeader,
    importHeader + "\n" + positionImport
  );
}

const placeholder = /export type Element = \s*\n\s*Node;/;
if (!placeholder.test(content)) {
  console.error(
    "postprocess.cjs: no se encontró el placeholder 'export type Element = Node;' en " +
      astTsPath +
      ". El output de tygo pudo haber cambiado de formato; revisar manualmente."
  );
  process.exit(1);
}

const replacement =
  "export type Element =\n  | " + ELEMENT_UNION.join("\n  | ") + ";";
content = content.replace(placeholder, replacement);

// The Go interface includes methods; the JSON-facing shape is BaseNode.
// tygo otherwise reduces its embedded Node interface to `any`.
const identityPlaceholder = /export type IdentityNode = \s*\n\s*Node;/;
if (!identityPlaceholder.test(content)) {
  console.error("postprocess.cjs: IdentityNode placeholder changed; review tygo output.");
  process.exit(1);
}
content = content.replace(identityPlaceholder, "export type IdentityNode = BaseNode;");

// Go keeps ThemeMode as string to preserve invalid authored values while the
// parser reports FRONT008, but JSON/TypeScript consumers only receive the
// two renderable schemes. Keep this replacement adjacent to the generated
// contract so schema-drift catches any tygo format change.
const themeModeField = "  theme_mode?: string;";
if (!content.includes(themeModeField)) {
  console.error(
    "postprocess.cjs: no se encontró theme_mode?: string en " + astTsPath +
      ". El output de tygo pudo haber cambiado de formato; revisar manualmente."
  );
  process.exit(1);
}
content = content.replace(themeModeField, '  theme_mode?: "light" | "dark";');

// The Go parser stores these as strings, while the JSON contract accepts
// exactly the two list marker classes.
for (const [field, typed] of [
  ["  listType: string;", '  listType: "ordered" | "unordered";'],
  ["  subListType?: string;", '  subListType?: "ordered" | "unordered";'],
]) {
  if (!content.includes(field)) {
    console.error("postprocess.cjs: list type field changed: " + field);
    process.exit(1);
  }
  content = content.replace(field, typed);
}

content = content.replace(/\n+$/, "\n");

fs.writeFileSync(astTsPath, content, "utf8");
console.log("postprocess.cjs: Element union aplicada en " + astTsPath);
